name: Deploy HTML Files

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: List files (debug)
      run: ls -la
    
    - name: Deploy HTML to Server
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.SSH_USERNAME }}
        TARGET: ${{ secrets.SSH_TARGET }}
        SOURCE: "./"                      # Copia todo el repositorio
        ARGS: "-rlgoDzvc --delete"
        EXCLUDE: "node_modules/, cypress/, .github/, doc/, .gitignore, cypress.config.js, package*.json, README.md"